### PR TITLE
All possible statuses for Student

### LINKED ISSUE #8: implement Statuses
enum Status with possible values

### PR DESCRIPTION
**Pull request by astutus**
Statuses are Implemented using enum type.
Resolves #8

### CODE REVIEW

**Review by Yankowski — COMMENTED** [review]
I suggest to change "Status" to "StudentStatus"

**Comment by bockowsk** [comment]
That's true, it wasn't too specific. I am going to change.

**Comment by bockowsk** [comment]
@Yankowski ok is has been changed. Please review.

**Comment by kkalista** [comment]
Hey, what about Students who failed in passing to the next year and will not repeat the year nor take a leave. Is there anything like Removed/Inactive etc.?

**Pull request merged**
